/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class jp_ac_nitech_hello_HelloJNI */

#ifndef _Included_client_h_
#define _Included_client_h_

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <pthread.h>

#include "../common/Common.h"
#include "../data/Signal.h"

#define BUFFSIZE 2048
#define ERR -1

#ifdef __cplusplus
extern "C" {
#endif

void *callBack(void *arg);
char *StrChomp(char *str);

typedef struct CallBackArgs {
	int socketFd;
	string socketPath;
	string sendData;
	string returnData;
} CallBackArgs;

class UnixDomainSocketManager {
private:
	int mSocketFd;
	string mSocketPath;
public:
	UnixDomainSocketManager(const string socketName);
	virtual ~UnixDomainSocketManager();
	int connectSocket();
	void closeSocket();
	string start(string data);
};

#ifdef __cplusplus
}
#endif
#endif
